(function(root){
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||cell==='')quoted=!quoted;else throw Error('Некорректные кавычки в CSV');}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Незакрытые кавычки CSV');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);const header=rows.shift()?.map(x=>x.trim());if(!header||['id','name','club','score','price','collected'].some(x=>!header.includes(x)))throw Error('Нужны столбцы id,name,club,score,price,collected');return validateCards(rows.map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]??'']))));}
function validateCards(cards){if(!Array.isArray(cards)||cards.length>10000)throw Error('Ожидается до 10000 карточек');const ids=new Set;return cards.map(c=>{if(!c||typeof c!=='object')throw Error('Некорректная карточка');const id=String(c.id??'').trim(),name=String(c.name??'').trim(),club=String(c.club??'').trim();const score=Number(c.score),price=c.price===''||c.price==null?null:Number(c.price);if(!id||!name||!club||ids.has(id)||!Number.isSafeInteger(score)||score<0||score>1e9||price!==null&&(!Number.isSafeInteger(price)||price<=0||price>1e9))throw Error('Проверь id, название, клуб, очки и цену (цена > 0 либо пустая)');ids.add(id);const v=c.collected;if(![true,false,'true','false','1','0','',undefined].includes(v))throw Error('collected должен быть true или false');return {id,name,club,score,price,collected:v===true||v==='true'||v==='1'};});}
function prune(states){states.sort((a,b)=>b.score-a.score||a.cost-b.cost);const kept=[];let cheapest=Infinity;for(const state of states){if(state.cost<cheapest){kept.push(state);cheapest=state.cost;}}return kept;}
function plan(cards,club,target,budget,slots=20){if(!club.trim())throw Error('Выбери клуб / набор');if(!Number.isSafeInteger(target)||target<=0||target>1e9||!Number.isSafeInteger(budget)||budget<0||budget>1e9||!Number.isSafeInteger(slots)||slots<=0||slots>100)throw Error('Укажи положительную цель, бюджет и число мест');const pool=cards.filter(c=>c.club.toLowerCase()===club.trim().toLowerCase()&&c.score>0&&(c.collected||c.price!==null));if(!pool.length)throw Error('Для этого клуба ещё нет подходящих карточек');const frontiers=Array.from({length:Math.min(slots,pool.length)+1},()=>[]);frontiers[0]=[{score:0,cost:0,chosen:[]}];for(let index=0;index<pool.length;index++){const card=pool[index],cardCost=card.collected?0:card.price;for(let used=frontiers.length-1;used>=1;used--){const additions=[];for(const state of frontiers[used-1]){const cost=state.cost+cardCost;if(cost<=budget)additions.push({score:Math.min(target,state.score+card.score),cost,chosen:[...state.chosen,index]});}if(additions.length)frontiers[used]=prune([...frontiers[used],...additions]);}}
const candidates=frontiers.flat();let best=candidates.filter(s=>s.score>=target).sort((a,b)=>a.cost-b.cost||a.chosen.length-b.chosen.length)[0];if(!best)best=candidates.sort((a,b)=>b.score-a.score||a.cost-b.cost||a.chosen.length-b.chosen.length)[0];const lineup=best.chosen.map(i=>pool[i]),selected=lineup.filter(c=>!c.collected);return {score:best.score,cost:best.cost,selected,lineup,reached:best.score>=target,slotsUsed:lineup.length,slots};}
function galleryPlan(input){
 const ids=[...new Set((input.pool||[]).map(Number).filter(Number.isSafeInteger))];
 const slots=Number(input.slots),target=Number(input.target),maxPrice=Number(input.maxPrice),budget=Number(input.budget);
 if(!Number.isSafeInteger(slots)||slots<1||!Number.isFinite(target)||target<0)throw Error('Некорректный набор Gallery');
 const held=new Set((input.collected||[]).map(Number));
 const scores=input.scores||{},prices=input.prices||{};
 const cards=[];
 for(const id of ids){const score=Number(scores[id]);if(!Number.isFinite(score)||score<=0)continue;const collected=held.has(id);const raw=Number(prices[id]);const price=collected?0:(Number.isSafeInteger(raw)&&raw>0?raw:null);if(!collected&&(price===null||price>maxPrice))continue;cards.push({id,score,price,collected});}
 if(cards.length<slots)return{reached:false,score:0,cost:0,lineup:[],missing:[],reason:'not-enough-cards',available:cards.length,needed:slots};
 const fronts=Array.from({length:slots+1},()=>[]);fronts[0]=[{score:0,cost:0,chosen:[]}];
 const trim=list=>{list.sort((a,b)=>b.score-a.score||a.cost-b.cost);const out=[];let cheapest=Infinity;for(const row of list){if(row.cost<cheapest){out.push(row);cheapest=row.cost;}}return out;};
 cards.forEach((card,index)=>{for(let used=slots;used>=1;used--){const add=[];for(const state of fronts[used-1]){const cost=state.cost+card.price;if(cost>budget)continue;add.push({score:Math.min(target,state.score+card.score),cost,chosen:[...state.chosen,index]});}if(add.length)fronts[used]=trim(fronts[used].concat(add));}});
 const final=fronts[slots];let best=final.filter(x=>x.score>=target).sort((a,b)=>a.cost-b.cost)[0];if(!best)best=final.slice().sort((a,b)=>b.score-a.score||a.cost-b.cost)[0];if(!best)return{reached:false,score:0,cost:0,lineup:[],missing:[],reason:'unreachable'};
 const lineup=best.chosen.map(i=>cards[i]);return{reached:best.score>=target,score:best.score,cost:best.cost,lineup,missing:lineup.filter(x=>!x.collected),reason:best.score>=target?null:'unreachable',available:cards.length,needed:slots};
}
root.GalleryCore={parseCSV,validateCards,plan,galleryPlan};if(typeof module!=='undefined')module.exports=root.GalleryCore;
})(typeof globalThis!=='undefined'?globalThis:this);
